# Generated by Django 3.2.7 on 2021-09-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(default=0)),
                ('price', models.FloatField(default=200.0)),
                ('occupied', models.BooleanField(default=False)),
                ('oceanside', models.BooleanField(default=False)),
                ('suite', models.BooleanField(default=False)),
            ],
        ),
    ]
