# Generated by Django 3.2.7 on 2021-10-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('timestamp', models.DateField(auto_now=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.employee')),
                ('guestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.guest')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
    ]
